workflows:
  build_ios:
    name: Build iOS App
    instance_type: mac_mini
    environment:
      vars:
        APP_ID: "com.paraguaycourier.app"
        BUNDLE_NAME: "Paraguay Courier"
      flutter: false
      xcode: latest
      node: 18
    scripts:
      - name: Install Dependencies
        script: |
          npm install -g @angular/cli
          npm install
      - name: Build Angular App
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Pod Install
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos -archivePath $CM_BUILD_DIR/build/App.xcarchive archive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/App.xcarchive -exportOptionsPlist ../exportOptions.plist -exportPath $CM_BUILD_DIR/build/export
    artifacts:
      - build/export/*.ipa